version: "3"
services:
  mongo1:
    image: mongo:5.0.2
    ports:
     - "27011:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    image: mongo:5.0.2
    ports:
      - "27012:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    image: mongo:5.0.2
    ports:
      - "27013:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

#rs.initiate(
#  {
#    _id: 'rs0',
#    members: [
#      {_id: 0, host: "mongo1:27017"},
#      {_id: 1, host: "mongo2:27017"},
#      {_id: 2, host: "mongo3:27017"}
#    ]
#  }
#)
